# 构建docker-compose项目
# docker-compose up -V --force-recreate
# docker-compose up -d --force-recreate
version: '3'
services:
  mysql:
    privileged: true
    container_name: jvue-mysql
    build:
      context: ./
      dockerfile: ./jvue-docker/jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      # 最好使用此设定时区，其它静像也可以使用,也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=testbugucms"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=123456"
    # 可以加--default-time-zone='+8:00'设定时区
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/db:/var/db
      - ./jvue-docker/jvue-mysql/my.cnf:/etc/my.cnf
      - ./data/mysql/log:/var/log
    restart: always