# 构建docker-compose项目
# docker-compose up --force-recreate
# docker-compose up -d --force-recreate
version: '3'
services:
  mysql:
    container_name: jvue-mysql
    build:
      context: ./
      dockerfile: ./jvue-docker/jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "TZ=Asia/Shanghai"
#    volumes:
#      - ./mysql/my.cnf:/etc/my.cnf
#      - ./mysql/db:/var/lib/mysql
#      - ./mysql/logs/mysql:/var/logs/mysql
    restart: always