version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: ./jvue-docker/jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'