# 构建docker-compose项目
# docker-compose --log-level INFO build
# docker-compose --log-level INFO build jvue-front

# 重启并清理以及重建容器
# docker-compose --log-level INFO up --force-recreate --remove-orphans
# docker-compose --log-level INFO up --force-recreate jvue-front

# 重启并重建镜像
# docker-compose --log-level INFO up --build --force-recreate --remove-orphans
# docker-compose --log-level INFO up --build --force-recreate jvue-front

# 启动守护线程
# docker-compose --log-level INFO up -d

# 重启并重建镜像启动守护线程
# docker-compose --log-level INFO up -d --build --force-recreate jvue-front

# oracle doc
# DB_SID
# This parameter changes the ORACLE_SID of the database. The default value is set to ORCLCDB.
# To connect from outside the container using SQL*Plus,
# $ sqlplus sys/Oradoc_db1@ORCLCDB as sysdba
# Changing default password for SYS user
# alter user sys identified by <new-password>;
# The database alert log can be viewed with
# $ docker logs <Oracle-DB>

version: '3'
services:
  jvue-mysql:
    image: jvue/mysql:5.7.24
    container_name: jvue-mysql
    build:
      context: ./
      dockerfile: ./jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      # 最好使用此设定时区，其它静像也可以使用,也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=bugucms4"
      - "MYSQL_USER=terwer"
      - "MYSQL_PASSWORD=123456"
    volumes:
      - ./data/mysql/db:/var/db
      - ./data/mysql/log:/var/log
      - ./jvue-mysql/my.cnf:/etc/my.cnf
      - ./jvue-mysql/init:/docker-entrypoint-initdb.d/
    restart: "no"