# 构建docker-compose项目
# docker-compose up -V --force-recreate
# docker-compose up -d --force-recreate
version: '3'
services:
  mysql:
    container_name: jvue-mysql
    build:
      context: ./
      dockerfile: ./jvue-docker/jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "TZ=Asia/Shanghai"
    volumes:
      - ./jvue-docker/jvue-mysql/my.cnf:/etc/my.cnf
      - ./data/mysql/log:/var/log
      - ./data/mysql/db:/var/lib/mysql
    restart: always