version: '3'
services:
  jvue-mysql:
    image: jvue/mysql:5.7.24
    container_name: jvue-mysql
    build:
      context: ./
      dockerfile: ./jvue-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      # 最好使用此设定时区，其它静像也可以使用,也可以用"TZ=Asia/Shanghai"
      - "TZ=CST-8"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=testbugucms"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=123456"
    volumes:
      - ./jvue-mysql/init:/docker-entrypoint-initdb.d/
    restart: always
